### ISSUE TITLE
Filter bundles by file data

### ISSUE THREAD

**Issue by BlueAmulet** [u-2018/LC-API#14]
Asset bundles start with "UnityFS" and a nul byte as the beginning of the data.
Maybe instead of filtering out certain extensions which tries to load .cfg and .pdb files as an example, read the first 8 bytes of the file and check if they are what is expected of a bundle.

**Comment by steven4547466** [comment]
All bundles start with this string?

**Comment by steven4547466** [comment]
#16 is merged. This will be released sometime tomorrow.
