### ISSUE TITLE
Can't exit the terminal after the 3.0 update

### ISSUE THREAD

**Issue by geekwrld** [u-2018/LC-API#28]
When using the terminal I cant tab out of the terminal or exit. Tested with the previous version 2.2.0 and it works normal.

**Comment by steven4547466** [comment]
Any other mods? LC API doesn't even do anything to the terminal afaik

**Comment by steven4547466** [comment]
I was unable to reproduce this with just LC API. There's potential that a mod hasn't updated to the latest version of LC API which contained breaking changes,

https://github.com/u-2018/LC-API/assets/23726534/84cc1ae1-6177-416f-851b-e70fde68aca5

**Comment by geekwrld** [comment]
I do have a few other mods so very possible there is a conflict there, I'll have to find out which one is doing this. Thank you

**Comment by geekwrld** [comment]
You are correct, it was the Glowstick mod that was causing the issue.
