### ISSUE TITLE
Is it possible to use LC_API to re-init other mods?

### ISSUE THREAD

**Issue by patrickdundas** [u-2018/LC-API#30]
Working on a mod that modifies some shared config / assets with another mod. Is it possible to use LC_API to reinit all or some mods?

**Comment by steven4547466** [comment]
Potentially, though I think BepinEx may not like that. We'll see.

**Comment by Lordfirespeed** [comment]
BepInEx supports hot-reloading out-of-the-box IIRC, it's the *mods* that don't.

Modders have to implement cleanup for hot-reload to work - unpatching all patches they applied with Harmony, for starters.

Not many put in the effort to do so.

**Comment by patrickdundas** [comment]
Thanks for the replies. I found a better option for my use case, as the mod I need to hot reload is open source and I can fork it to expose the functions I need to reinit.
