### ISSUE TITLE
Terminal and Esc

### ISSUE THREAD

**Issue by Niconoko** [u-2018/LC-API#31]
https://pastebin.com/eAC3jUE6
Here's the log around when it happens, me open terminal when the game start is fine, playing just fine, until relog at some point, can no longer click esc and when click into terminal, can't close it.

Not sure what's going on, but when try to exit, the log mention this mod. Thx in Adv. :3

**Comment by steven4547466** [comment]
See #28 and let me know if it's the same issue.

**Comment by Niconoko** [comment]
It was Terminal Game mod and it's API from what me have removed and it's back to normal so far. *Maow* :3
