### ISSUE TITLE
 Unable to open archive file

### ISSUE THREAD

**Issue by rogedkone** [u-2018/LC-API#32]
Unable to open archive file: C:/Steam/SteamApps/Common/Lethal Company/BepInEx/plugins/2018-LC_API/Bundles/networking
2.2.0 - work
3.0.0 - broke
3.0.1 - broke

![image](https://github.com/u-2018/LC-API/assets/85563010/f1c52143-ae42-4d29-9aa3-feec23f76272)

**Comment by ChristianNguyen-Chinag** [comment]
The file its looking for is packed as plugins/bundles/networking but the code is searching for plugins/2018-LC_API/Bundles/networking. If you add the 2018-LC_API folder manually it works properly.
