### ISSUE TITLE
Problem with version 3.0.0 and later

### ISSUE THREAD

**Issue by K4stic** [u-2018/LC-API#34]
I have this bug only with version 3.0.0  and later because with version 2.2.0 all works perfectly no problems.

So the Problem is as a host i create a lobby but my char is stuck mid air and i can't move,run or do anything that's the problem.
mouse works and i can do 360 x) the ojnly think i can i added a pic

![Untitleergsfdgfsgfsd](https://github.com/u-2018/LC-API/assets/154697963/02d3131f-3959-4e15-b410-c732c4a5b7a9)

**Comment by steven4547466** [comment]
What other mods do you have installed?

**Comment by Mexes-GM** [comment]
this error happened to me, it was caused by the BetterStamina mod.

**Comment by steven4547466** [comment]
See above. Reopen if you can reproduce it with just LCAPI
