### ISSUE TITLE
API

### ISSUE THREAD

**Issue by killjoymatic** [u-2018/LC-API#42]
**So, the mod used to work for me, and then I updated it and it stopped working, this is my BepinEx output log.**

**I am running on Ubuntu with proton, I have all of the mods in the main directory, I tried downloading an older version of the API and I don't get the same error message.
I don't know what changed between then and now other than the version of the API, any insight would be helpful.**

**This output is without any other mods than BepinEx and LC_API loaded so that I could isolate the problem.**

**It seems that the new version isn't loading the networking bundle in unity.**

[Message:   BepInEx] BepInEx 5.4.22.0 - Lethal Company (12/23/2023 8:59:18 PM)
[Info   :   BepInEx] Running under Unity v2022.3.9.15351836
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.22.0]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [LC_API 3.0.2]
[Warning:    LC_API] 
.____    _________           _____  __________ .___  
|    |   \_   ___ \         /  _  \ \______   \|   | 
|    |   /    \  \/        /  /_\  \ |     ___/|   | 
|    |___\     \____      /    |    \|    |    |   | 
|_______ \\______  /______\____|__  /|____|    |___| 
        \/       \//_____/        \/                 
                                                     
[Info   :    LC_API] LC_API Starting up..
[Message:   BepInEx] Chainloader startup complete
[Message:    LC_API] BundleAPI will now load all asset bundles...
[Message:    LC_API] BundleAPI got no assets to load from legacy directory
[Message:    LC_API] BundleAPI got 1 AssetBundles to load!
[Message:    LC_API] Got asset for load: assets/lc_api/itemnetworkingprefab.prefab
[Message:    LC_API] Loaded asset: ItemNetworkingPrefab
[Message:    LC_API] Got asset for load: assets/lc_api/playernetworkingprefab.prefab
[Message:    LC_API] Loaded asset: PlayerNetworkingPrefab
[Message:    LC_API] BundleAPI finished loading all assets.
[Message:    LC_API] BundleAPI finished loading all assets.
[Info   :    LC_API] LC_API Started!
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: 0.55
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: 0.55; (0.00, 0.00, 0.00, 0.55) (True)
[Info   : Unity Log] Saving changed settings
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: 0.55
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: 0.55; (0.00, 0.00, 0.00, 0.55) (True)
[Info   : Unity Log] subcribing to steam callbacks
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: 0.55
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: 0.55; (0.00, 0.00, 0.00, 0.55) (True)
[Error  : Unity Log] Unable to open archive file: Z:/home/half/.local/share/Steam/steamapps/common/Lethal Company/BepInEx/plugins/2018-LC_API/Bundles/networking
[Error  : Unity Log] Failed to read data for the AssetBundle 'Z:\home\half\.local\share\Steam\steamapps\common\Lethal Company\BepInEx\plugins\2018-LC_API\Bundles\networking'.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LC_API.BundleAPI.BundleLoader.LoadAssetBundle (System.String filePath, System.Boolean cache) (at <b80ae8dfe06446589042df100ce5b1b5>:0)
LC_API.GameInterfaceAPI.Events.Patches.Internal.GameNetworkManagerStartPatch.Postfix (GameNetworkManager __instance) (at <b80ae8dfe06446589042df100ce5b1b5>:0)
(wrapper dynamic-method) GameNetworkManager.DMD<GameNetworkManager::Start>(GameNetworkManager)

[Info   : Unity Log] [FacepunchTransport] - Initialized access to Steam Relay Network.
[Info   : Unity Log] [FacepunchTransport] - Fetched user Steam ID.
[Info   : Unity Log] Set version num
[Info   : Unity Log] Changing gamma
[Info   : Unity Log] override float value: 0.55
[Info   : Unity Log] Overriding float
[Info   : Unity Log] Gamma changed
[Info   : Unity Log] Set gamma to new value: 0.55; (0.00, 0.00, 0.00, 0.55) (True)

**Comment by steven4547466** [comment]
Hm. I tried recreating this by enabling legacy asset loading, but it seemed to work fine on my end. Can you send me your mod list?

**Comment by adrianbeys** [comment]
the same problem:
[Error  : Unity Log] Unable to open archive file: C:/Program Files (x86)/Steam/steamapps/common/Lethal Company/BepInEx/plugins/2018-LC_API/Bundles/networking
[Error  : Unity Log] Failed to read data for the AssetBundle 'C:\Program Files (x86)\Steam\steamapps\common\Lethal Company\BepInEx\plugins\2018-LC_API\Bundles\networking'.

tool mod: BepinEx 5.4.2100
mod list: 
- MoreCompany 

Only :)

**Comment by killjoymatic** [comment]
> Hm. I tried recreating this by enabling legacy asset loading, but it seemed to work fine on my end. Can you send me your mod list?

I considered that so I tried to reduce the mod list to the absolute minimum, so I did a fresh install of the game with just the basics.
I started it first with just;
-BepinEx 5.4.2100 or BepinEx 5.4.22.0
and
-LC_API

to see if I got the same error, and I did, but after that I installed:
-More Company
-Late Company

It would crash when attempting to host, and produce an "An error has occurred" when I tried to join a lobby.

**Comment by Anthony6996** [comment]
Hello, I have the same exact issue, with bepinex 5.4.2100 the networking file gives the error (same one as posted above). All mods do not work, the pause/settings menu does not work, and I can only quit the game using alt + f4. With bepinex 5.4.22.0 I don't have that error in the log output file but I still have the same exact issues.

I was only able to fix this using a previous version of LC_API and deleting the current Bundles folder, which has the networking file inside. It also seems to create three more "players" that do not move, you can see the screenshot [here](https://imgur.com/a/5SA7wXK)

My current mod list is:

- Helmet Cameras
- More_Emotes
- Reserved flashlight slot
- LateCompany
- ShipLoot
- Bepinex pack
- LC_API 1.5.0.0
- Boombox controller
- Skinwalkers
- ItemQuickSwitch
- BiggerLobby

**Comment by adrianbeys** [comment]
> > Hm. I tried recreating this by enabling legacy asset loading, but it seemed to work fine on my end. Can you send me your mod list?
> 
> I considered that so I tried to reduce the mod list to the absolute minimum, so I did a fresh install of the game with just the basics. I started it first with just; -BepinEx 5.4.2100 or BepinEx 5.4.22.0 and -LC_API
> 
> to see if I got the same error, and I did, but after that I installed: -More Company -Late Company
> 
> It would crash when attempting to host, and produce an "An error has occurred" when I tried to join a lobby.


alternative solution (at the moment):
download version LC_API-2.2.0

**Comment by AlexFerras** [comment]
Was able to fix this issue by placing the "networking" bundle to BepInEx\plugins\2018-LC_API\Bundles. Seems like LC_API looks for it in the wrong directory.

**Comment by steven4547466** [comment]
The Bundles folder *should* be in the `plugins\2018-LC_API` folder. The `Bundles` folder in `\plugins` is not used. If you are downloading via a mod manager it will resolve the structure for you. I'll put some manual installation instructions in the README since this seems to be a recurring issue with manual installations.

But for future reference, the entire `plugins` folder of the zip file should go into `plugins\2018-LC_API` as that's what thunderstore expects. Your resulting file structure, should look like this:
![cdggtj_17955 1](https://github.com/u-2018/LC-API/assets/23726534/7add4fe4-3f1e-4891-b689-67da962c7399)

Or in text:
```
BepinEx
├───Bundles
├───cache
├───config
├───core
├───patchers
└───plugins
        └───2018-LC_API
        │   icon.png
        │   LC_API.dll
        │   manifest.json
        │   README.md
        │
        └───Bundles
                networking
```

**Comment by steven4547466** [comment]
If the above does not fix your issue, reopen.
