### ISSUE TITLE
Cannot interact with almost anything if I'm the host

### ISSUE THREAD

**Issue by Czekoloczek** [u-2018/LC-API#51]
When i create a game i can't interact with the terminal, i can't start the game, i can't open the pause menu and there are 3 dummys with the name `player#`
https://github.com/u-2018/LC-API/assets/76474182/557ccd73-bb82-43d1-ae6f-d8b4c154faac

**Comment by ghost** [comment]
This is also happening to me

**Comment by steven4547466** [comment]
Please follow the manual installation instructions given here: https://github.com/u-2018/LC-API?tab=readme-ov-file#manual

Just dragging and dropping the files will not work.

**Comment by Czekoloczek** [comment]
It works now, thanks

I just have 2 suggestions:
- Copy and paste the Installation instructions to the LC API Thunderstore page
- Add the `2018-LC_API` folder in the .zip that you download from the Thunderstore page (i think it's way more common for users to just drag and drop files)

**Comment by steven4547466** [comment]
> Add the 2018-LC_API folder in the .zip that you download from the Thunderstore page (i think it's way more common for users to just drag and drop files)

If I do this it will break the mod manager installation, so I can't

> i think it's way more common for users to just drag and drop files

I know for a fact it isn't based on the download stats on thunderstore.

> Copy and paste the Installation instructions to the LC API Thunderstore page

This is a good idea and I forgot about it. I will do that in the next release.
