### ISSUE TITLE
can't join with other

### ISSUE THREAD

**Issue by 3boodyxz** [u-2018/LC-API#56]
I found this issue with my friend too. I can't join with people even if they're (moded) only if I delete the LC-API mod.
*It shows an "error occurred" massage.

**Comment by steven4547466** [comment]
Can you send some screenshots and a mod list?

**Comment by mks812** [comment]
I also have this problem after I wanted to install boombox mod with LC-API
![2023-12-28 23_17_27-plugins](https://github.com/u-2018/LC-API/assets/155114937/639239e4-b5f8-4a31-aef1-6bfda84c4296)
normal people can join my server but others with LC-API cant, some error about steam user 0

**Comment by steven4547466** [comment]
~~I can't access your image, you should just be able to drag and drop it into the comment box~~

I can now for some reason. It seems like you are manually installing, did you follow the manual installation instructions in the [readme](https://github.com/u-2018/LC-API?tab=readme-ov-file#manual)

**Comment by mks812** [comment]
ye I had it in 2018-LC_blahblah, it was working, the problem was that my friend couldnt join me while he also had the mod. Some random players were joining me and they probably were vanilla

**Comment by steven4547466** [comment]
Could you remove all your mods except for LC API and see if the problem still happens?

**Comment by Undertimes** [comment]
Same issue here. Cannot join any lobby, modded or vanilla, while using LC_API above version 3.0. 

Installed through Thunderstore. I removed all other mods except LC_API, problem still occured. I removed LC_API and it worked again.

I tried different versions. When switching back to 2.2.0 the issue does not occur, but anything above that (3.0 and more) has this issue.

**Comment by gregggehman** [comment]
Same issue. 

This is what was in BepInEx log:
[Warning: Unity Log] [Netcode] NetworkConfig mismatch. The configuration between the server and client does not match

**Comment by 3boodyxz** [comment]
> Can you send some screenshots and a mod list?

sorry, for the late response about the mod list I tried to use it without any mod but it also doesn't work. I also tried version 2.2.0 and it worked but any higher version didn't.

**Comment by steven4547466** [comment]
See the issue [here](https://github.com/steven4547466/LC-API/issues/12) where I will be tracking this in the future
