### ISSUE TITLE
Remove OnDestroy

### ISSUE THREAD

**Issue by legoandmars** [u-2018/LC-API#6]
Some of this mod's initialization is done in an OnDestroy method. This is unintended behaviour, and the only reason it works is because a glitch in BepInEx is causing plugins to be destroyed

You should be able to move everything in OnDestroy to the end of Awake(), and it should retain the same behaviour.
Once everything is moved over the community should be able to enable the "Hide Manager GameObject" option on the config, and then you won't have to create a new GameObject to use Update()

**Comment by xiaoxiao921** [comment]
This is not a bepinex glitch but just an unity engine quirk (irrelevant for everyone but modders)
If possible a team should provide a bepinex pack that ship with a custom bepinex config file that set a custom Preloader Entrypoint, the assembly to target should be Assembly-CSharp and the Type / Method entries should be set to the first one coming from the game assembly, you can find those through ctorshotgun https://github.com/BepInEx/BepInEx.Debug#ctorshotgun

**Comment by legoandmars** [comment]
"BepInEx glitch" was definitely the wrong way to word it, but no matter how it's fixed this plugin will be missing core functionality because it's inherently expecting the plugin object to be destroyed

**Comment by xiaoxiao921** [comment]
I don't see any future in this plugin anyway, the license need to be changed asap or another api will simply be made and replace this one as if you want to get anywhere in a modding community you need the community to be participating, as obvious as it sounds.

**Comment by u-2018** [comment]
The API should now be able to load no matter if the Hide Manager GameObject option is on or off.
