### ISSUE TITLE
3.1.0 version has several issues

### ISSUE THREAD

**Issue by MamaSantaLucia** [u-2018/LC-API#61]
I can't change place of any object, can't open menu on Esc, can't open terminal ( I can try to do it at the first time on E, but then it seems that terminal is occupied by someone and I can't interfere with it anymore). I also have 3 random players, as if they joined with me. 
Here's the list of modes I'm using.
![Снимок экрана 2023-12-29 161825](https://github.com/u-2018/LC-API/assets/93881547/253699b0-6725-4e3b-a139-fb411fb54d44)
It's worth noting that I don't have these problems with previous version 3.0.2.

**Comment by steven4547466** [comment]
Please follow the [manual install instructions](https://github.com/u-2018/LC-API/tree/dev?tab=readme-ov-file#manual) next time as I can visually see you're missing the the folder.

- Create a new folder there called `2018-LC_API`
- Move `LC_API.dll` and the `Bundles` folder in there
- Ensure inside the `Bundles` folder is a file called `networking`.
```
BepinEx
├───Bundles
├───cache
├───config
├───core
├───patchers
└───plugins
        └───2018-LC_API
        │   LC_API.dll
        │
        └───Bundles
                networking
```
